### ISSUE TITLE
Errors in the doc

### ISSUE THREAD

**Issue by sinsunsan** [seegno/angular-oauth2#13]
Under 
https://github.com/seegno/angular-oauth2#oauthtokenprovider
Section

You have written
```javascript
OAuthProvider.configure({
  name: 'token',
  options: {
    secure: true
  }
});
```
I think in this context it's 
```javascript
OAuthTokenProvider.configure({
  name: 'token',
  options: {
    secure: true
  }
});
```
Am I wrong ?

**Comment by ruipenso** [comment]
@sinsunsan You're right! Thanks for pointing this out.
