### ISSUE TITLE
Change payload type in getAccessToken() to JSON instead of query string

### ISSUE THREAD

**Issue by JesseObrien** [seegno/angular-oauth2#20]
Hi, I'm wondering if there's any way to change the payload that the getAccessToken() request sends off to JSON instead of a query string? I can pass custom headers to the function to change it to `Content-Type`: `application/json` but I can't change the payload because it's doing a stringify and passing the data as a query string.

https://github.com/seegno/angular-oauth2/blob/04f0070ef28d2c7ac036627921bcfa3091a0daa8/src/providers/oauth-provider.js#L132

**Comment by nunofgs** [comment]
I believe [section 4.3.2](https://tools.ietf.org/html/rfc6749#section-4.3.2) of the OAuth2 RFC requires that, when using the grant_type `password`, the body must be encoded as `application/x-www-form-urlencoded`.

**Comment by JesseObrien** [comment]
Right, that's what I thought, thanks.
