### ISSUE TITLE
OAuthToken not being set after getAccessToken() success.

### ISSUE THREAD

**Issue by JesseObrien** [seegno/angular-oauth2#21]
Hi, I'm doing `OAuth.getAccessToken(credentials)` and getting a successful hit on the server. The token is coming back fine, nothing wrong with request cycle. The issue happens when I call `OAuth.isAuthenticated()` after `getAccessToken()` runs, it always returns false. I stepped through the code and have a screenshot below. It looks like the `OAuthToken.token` is still undefined even after being set directly when the request comes back successful. I have the `response.data` on the right side and the breakpoint set right after the token should be set. Any help would be appreciated :)

![](https://i.imgur.com/xBmbiHE.png)

**Comment by ruipenso** [comment]
Are you using `https`? If so, you'll need to configure OAuthToken to accept a `secure` cookie, e.g., 

```
OAuthTokenProvider.configure({
  name: 'token',
  options: {
    secure: true,
    path: '/'
  }
});
```

We'll consider to add this automatically to `OAuthTokenProvider`.

**Comment by JesseObrien** [comment]
Hah, I'm currently just doing `http` calls and not `https` but the default token options have `secure: true`. I changed that to false and it's working now. Thanks a lot!

**Comment by nicogarcia** [comment]
Please, warn in the README that using 'http' with default OAuthTokenProvider configuration would lead to have token undefined. In a previous attempt to use the library, I gave up using it because of this. In this attempt I fortunately read this issue! Thanks!

**Comment by ruipenso** [comment]
@nicogarcia Thanks for reporting your issue. I created an [issue](https://github.com/seegno/angular-oauth2/issues/22) to fix this in a more clever way. I'll probably be able to fix this next week.

**Comment by jguittard** [comment]
:

**Comment by quocble** [comment]
Thanks goodness for this issue. I encountered exact same issue.
