### ISSUE TITLE
Change to new angular $cookies service

### ISSUE THREAD

**Issue by joaogranado** [seegno/angular-oauth2#24]
We should change to new `$cookies` released with angular 1.4.0-beta.6. Since we were using `ipCookie` only because it was possible to pass additional `options` so we could set important flags such as `secure`. It's important to note this is a breaking change, and will require to angular 1.4 and above, and since the current version is still beta, this will be released at the same time of angular 1.4 stable.

**Comment by ruipenso** [comment]
+1

**Comment by nicogarcia** [comment]
+1
