### ISSUE TITLE
oauth:error event customization

### ISSUE THREAD

**Issue by LennyLip** [seegno/angular-oauth2#31]
oauth:error now is

```{ status: 400, data: { error: 'invalid_grant' }```

can i customize it?

i'm get error from my pytonhlib https://github.com/idan/oauthlib as:

```{"error": "invalid_grant", "error_description": "Invalid credentials given."}```

and http status code

```Status Code:401 UNAUTHORIZED```

**Comment by LennyLip** [comment]
hm, via https://tools.ietf.org/html/rfc6749#section-5.2 it seems problem in my server lib. Problem in 401 status code only (must be 400).

**Comment by mfagadar** [comment]
@LennyLip I had a similar question reported here: https://github.com/seegno/angular-oauth2/issues/32#issuecomment-88888755. The solution was to handle the custom errors via an interceptor.
