### ISSUE TITLE
OAuthToken.removeToken() modifies config.options

### ISSUE THREAD

**Issue by nicogarcia** [seegno/angular-oauth2#33]
I'm having trouble with OAuthToken.removeToken(), I debugged my application and found that ipCookies modifies config.options and so, in the next use of config.options it has 'exipires' set to an invalid date. Should it be passed a copy of config.options to ipCookie.remove()?
I vote for the ngCookies implementation that is waiting to be merged, will it be merged?
Thanks!

**Comment by joaogranado** [comment]
When you say that ipCookie sets `expires` to an invalid date do you mean it is set to `Thu, 01 Jan 1970 00:00:00 GMT`? If you don't pass any option to `ipCookie.remove()` it forces cookie expiration. #24  (ngCookies implementation) will be merged when the stable version o angular (1.4), since IMO it would be quite unreasonable if we merge something depending on an unstable API, which could change until then. Otherwise, you're free to override the current implementation with a decorator, as described here #19 for instance.

**Comment by ruipenso** [comment]
@nicogarcia #25 can only be merged with the release of angular 1.4 stable.

`OAuthToken.removeToken()` is using `config.options` which you can configure. Internally, they change the `expires` to force the cookie expiration.

Can you show a snippet of your code? Probably the problem you're having is other, perhaps the cookie path? :)

**Comment by nicogarcia** [comment]
I'm sorry I said invalid date because that were Chrome inspector words, yes, it was some day of 1969.
I solved the problem by using angular.copy(config.options) in bower_components code and I'm sure there's no worst way to do it :P

```
function OAuthTokenProvider() {
        var config = {
            name: "token",
            options: {
                secure: true
            }
        };
        this.configure = function(params) {
            if (!(params instanceof Object)) {
                throw new TypeError("Invalid argument: `config` must be an `Object`.");
            }
            angular.extend(config, params);
            return config;
        };
        this.$get = function(ipCookie) {
            var OAuthToken = function() {
                function OAuthToken() {}
                _prototypeProperties(OAuthToken, null, {
                    token: {
                        set: function(data) {
                            return ipCookie(config.name, data, config.options);
                        },
                        get: function() {
                            return ipCookie(config.name);
                        },
                        enumerable: true,
                        configurable: true
                    },

                    // ..... Code removed to shorten issue ....
                    removeToken: {
                        value: function removeToken() {
                            // Here, ipCookie modifies config.options and in next use of those options
                            // they have 'expires' set to 1969
                           // (This is how I solved it temporarily)
                            return ipCookie.remove(config.name, angular.copy(config.options));
                        },
                        writable: true,
                        enumerable: true,
                        configurable: true
                    }
                });
                return OAuthToken;
            }();
            return new OAuthToken();
        };
        this.$get.$inject = [ "ipCookie" ];
    }
```

My configuration is this one:

```
.config(['OAuthProvider', 'OAuthTokenProvider', function (OAuthProvider, OAuthTokenProvider) {
    OAuthProvider.configure({
      baseUrl: 'http://localhost:8080',
      clientId: 'CLIENT_ID',
      grantPath: '/oauth/token'
    });

    OAuthTokenProvider.configure({
      options: {
        secure: false
      }
    });
  }])
```
I'm using OAuth.getAccessToken() and it's successful in the first time, but second time it fails and doesn't store the cookie.

Thanks for your help!

**Comment by LennyLip** [comment]
+1 for this issue
after revokeToken(), in getAccessToken() this: 

OAuthToken.token = response.data;

does not work, OAuthToken.token got undefined.

angular.copy helps, thanks @nicogarcia !

**Comment by rllola** [comment]
I have the same issue. Does there is a solution for that ?
Thanks
