### ISSUE TITLE
RevokeToken not sent Auth

### ISSUE THREAD

**Issue by LennyLip** [seegno/angular-oauth2#34]
https://tools.ietf.org/html/rfc7009#section-2.1

   The client also includes its authentication credentials as described
   in Section 2.3. of [RFC6749].

https://github.com/seegno/angular-oauth2/blob/04f0070ef28d2c7ac036627921bcfa3091a0daa8/src/providers/oauth-provider.js#L183

**Comment by joaogranado** [comment]
The problems you're describing is that the token is not being sent or are you saying we didn't implemented it properly?

**Comment by joaogranado** [comment]
Are you saying that the token is not being sent or  we didn't implemented it properly?

**Comment by LennyLip** [comment]
token is sent, but we need to send cliend_id and client_secret too.

example - this server lib test Auth when revoke.
https://github.com/evonove/django-oauth-toolkit/blob/d2cde74695256a1251a575a377bbb34c759cacbf/oauth2_provider/oauth2_validators.py#L47

Another question - why we send RefreshToken, but not Token , when Revoke?

My server deleted RefreshToken when Revoke, but Token is steel exist in DB and i can get "Authorization:Bearer" access to my API. May be we need to send Token (Not RefreshToken) when revoke?

**Comment by ruipenso** [comment]
@LennyLip As I see it, the only thing we're missing here is the `token_type_hint` reported on #16.

[RFC7009](https://tools.ietf.org/html/rfc7009#section-2.1) says

> [...] If the particular token is a refresh token [...] then the authorization server SHOULD also invalidate all access tokens. If the token passed to the request is an access token, the server MAY revoke the respective refresh token as well.

So, if you have a `refresh_token`, revoking it should be enough. Your OAuth server should be able to handle this automatically. You should report this issue there.

Also relevant, [RFC6749](https://tools.ietf.org/html/rfc6749#section-6) says

>  The authorization server MAY issue a new refresh token, in which case the client MUST discard the old refresh token and replace it with the new refresh token. The authorization server MAY revoke the old refresh token after issuing a new refresh token to the client.

We'll implement the `token_type_hint` though.

Thanks.

**Comment by LennyLip** [comment]
@ruipenso 
Ok, refresh_token revoking it should be enough, thank you.

But what about subject issue?

https://tools.ietf.org/html/rfc7009#section-2.1

The client also includes its authentication credentials as described
in Section 2.3. of [RFC6749].
