### ISSUE TITLE
How to get the result from getAccessToken?

### ISSUE THREAD

**Issue by fndmiranda** [seegno/angular-oauth2#42]
How to get the result from getAccessToken?
eg:
```JavaScript
var result = OAuth.getAccessToken({username: $scope.data.email, password: $scope.data.password});
```
To get the return webservice messages...

**Comment by ruipenso** [comment]
Hi @fndmiranda.

`getAccessToken` is a promise, so you can do

```
OAuth.getAccessToken(data)
  .then(function(response) {
    // ...
  })
  .catch(function(response) {
    // ...
  });
```

The `token` will be stored on success and we are also emitting an event `oauth:error` when errors occurred - take a look at [oauth-interceptor.js](https://github.com/seegno/angular-oauth2/blob/master/src/interceptors/oauth-interceptor.js#L19).

I hope this helps.

**Comment by fndmiranda** [comment]
Hi @ruipenso 

Thank you, it worked, taking advantage, how could I get the user information authenticated? Type the first name.

Its authenticate using only the username and password with OAuth2?

**Comment by ruipenso** [comment]
Hi @fndmiranda,

This module is only responsible for `oauth`. Once you get the `access_token`, every call send the `Authorization` header.

To get any private information about the user, you'll need to make the respective a call to your API.
