### ISSUE TITLE
A little bit of concern.

### ISSUE THREAD

**Issue by mr-mig** [seegno/angular-oauth2#5]
Correct me if I am wrong, but this is a bad idea to store the clientId and secret on the client side:
```
OAuthProvider.configure({
      baseUrl: 'https://api.website.com',
      clientId: 'CLIENT_ID',
      clientSecret: 'CLIENT_SECRET',
    });
```

**Comment by ruimarinho** [comment]
This is only adequate when your client type is `public`. From http://tools.ietf.org/html/rfc6749#section-2.1:

> Clients incapable of maintaining the confidentiality of their credentials (e.g., clients executing on the device used by the resource owner, such as an installed native application or a web browser-based application), and incapable of secure client authentication via any other means.

Depending on the server side implementation, usually `clientSecret` is not even required because, as you say, it can't be trusted.

Maybe this should be added to the README. /cc @ruipenso

**Comment by ruipenso** [comment]
@mr-mig @ruimarinho That's right. I'll create an issue to make `clientSecret` optional. Thanks.

**Comment by brice** [comment]
Any news?
