### ISSUE TITLE
Problems with Webpack

### ISSUE THREAD

**Issue by joselo** [seegno/angular-oauth2#54]
Hi Guys,

I'm trying to use angular-oauth2 with webpack, but I get this error

![Chrome Inspector](https://s3.amazonaws.com/f.cl.ly/items/300N3d3f030a023O1p3R/Developer_Tools_-_http___instafac_dev_8080_.png)

Any idea?

I installed as you mention in the README file, but when I try to call it, seems like it try to read the local bower packages 

```javascript
require('angular');
require('angular-cookies');
require('query-string');
require('angular-oauth2');
```

even if i use

```javascript
require('../../node_modules/angular-oauth2/dist/angular-oauth2.min.js');
```

**Comment by ruipenso** [comment]
You still need to run `bower install`.
BTW, using NPM you can use the original source module.

**Comment by joselo** [comment]
Thanks for your answer, I installed angular-oauth2 with bower, I'm getting this error now, But I guess is something else, I'm trying to solve it.

![Chrome Inspector](https://s3.amazonaws.com/f.cl.ly/items/3y323T0Z1D2d0D2Q1Z3C/Instafac.png)

![Chrome Inspector](https://s3.amazonaws.com/f.cl.ly/items/430U0r1t0m0f1e0O1C21/Instafac.png)

Thanks

**Comment by ruipenso** [comment]
Did you resolved your problem?

Closing the issue, doesn't seems to be a `angular-oauth2` problem.

**Comment by canaydogan** [comment]
I have the same issue. I got this error:
![screen shot 2015-09-02 at 10 40 29](https://cloud.githubusercontent.com/assets/620273/9625476/19301b5e-515f-11e5-971e-3b00a47876a2.png)

**Comment by rob-balfre** [comment]
Same issue here, doesn't look like webpack and angular-oauth2 like each other
