### ISSUE TITLE
There is no min version of query-string

### ISSUE THREAD

**Issue by jensstalder** [seegno/angular-oauth2#55]
The readme states that the inclusion of query-string.min.js is required, yet there is no such thing.

**Comment by laurenmacam** [comment]
had the same problem, so I installed through Bower and the query-string.js appeared

**Comment by ruipenso** [comment]
Right! There's no minified version of `query-string`.

All the dependencies can be installed thought bower or downloaded if you don't want to use bower.

We should update the README.
