### ISSUE TITLE
'angular' is undefined

### ISSUE THREAD

**Issue by anita18** [seegno/angular-oauth2#56]
I have downloaded angular-oauth2 and used the steps as mentioned in the documentation. When i run my application i get this error.

"Cannot read property 'module' of undefined " at this line 
" var ngModule = angular.module("angular-oauth2", [ "ngCookies" ]).config(oau..."

**Comment by ruipenso** [comment]
Have you imported `angular`?

Don't think this is a problem with `angular-oauth2`.

**Comment by anita18** [comment]
Yes. But I guess its older version issue. I am using angular V1.2.11 version. That might be issue.

**Comment by ruipenso** [comment]
@anita18 You need to use `angular 1.4.*` for the latest version (`angular-oauth2 3.*`). Or, `angular 1.3.*` for `angular-oauth2 2.*`.

**Comment by anita18** [comment]
Yes sure.
