### ISSUE TITLE
Refresh token and http asynchronus queue

### ISSUE THREAD

**Issue by girod** [seegno/angular-oauth2#57]
There is a bug when we use getrefreshtoken if the page has sent multiple asynchronus http requests. Because all the http requests 'refresh_token' are sent with the first access token ... The first request is ok : we get the new access token but the next requests in the queue use the old access token. So we get a 401 error ...

**Comment by pashamesh** [comment]
+1

**Comment by ruipenso** [comment]
The changes introduced in #77 solves this issue. Closing it.

**Comment by ruipenso** [comment]
These chances was reverted and re-introduce in a major version (4.0.0) due to BC. See this [comment](https://github.com/seegno/angular-oauth2/pull/77#issuecomment-183305389) for more information.
