### ISSUE TITLE
Problem on module inject

### ISSUE THREAD

**Issue by auriga1** [seegno/angular-oauth2#58]
I'm building a project with ionic framework.
When I inject 'angular-oauth2' on my root module I have this error:

Uncaught Error: [$injector:unpr] Unknown provider: $$cookieReaderProvider <- $$cookieReader <- $cookies <- OAuthToken <- oauthInterceptor <- $http <- $templateFactory <- $view <- $state <- $cookies

I tried with module angular-cookies from angular and with angular-cookie from ivpusic

**Comment by joaogranado** [comment]
Hey @auriga1. Which angular version are you using in your project? angular-oauth2 requires angular >=1.4 because it uses the new ngCookies. Do you have the latest ngCookies in your project dependencies?

**Comment by auriga1** [comment]
Thank you very much :)
I have angular@1.3.13

What can I do? I downloaded angular-cookies starting from the link on the homepage of this project!

**Comment by joaogranado** [comment]
You should download the latest angular release (1.4.3) and the angular cookies module as well (1.4.3). This should solvethe issue :)

**Comment by auriga1** [comment]
Yes you are right,
the fact is that actually I'm using Ionic Framework and it's last release include Angular 1.3.
Reading on the web it seems that there is not an easy way to upgrade to 1.4 without the risk to loose stability.

I hope next subversion will include angular@1.4

Thank you very much for reply

**Comment by ruipenso** [comment]
You can use [2.2.1](https://github.com/seegno/angular-oauth2/tree/2.1.1).

**Comment by auriga1** [comment]
@ruipenso: thanks for reply. I can't find version 2.2.1 dependecies. Does it works with Angular 1.3.13?

**Comment by ruipenso** [comment]
Yes.

https://github.com/seegno/angular-oauth2/blob/2.1.1/bower.json

```
"dependencies": {
  "angular": "^1.3.9",
  "angular-cookie": "^4.0.6",
  "query-string": "^1.0.0"
}
```

**Comment by auriga1** [comment]
thx
