### ISSUE TITLE
Authorization header missing

### ISSUE THREAD

**Issue by PeterSawyer** [seegno/angular-oauth2#61]
Howdy seegno devers,

I have been trying to implement your library but cannot get it to perform the initial auth successfully.  I am currently talking to a Java Spring-boot server running in a virtual box.

I can achieve the result using **curl** as per: -

```
curl -X POST -vu clientId:clientSecret http://192.168.56.2:8080/oauth/token -d 'username=username&password=password&grant_type=password'

{"access_token":"1b9186ae-cf63-454f-8424-12878cee7147","token_type":"bearer","refresh_token":"1fac8562-b6bf-4a06-bd39-6c439fd685ac","expires_in":35417,"scope":"read write"}
```

But when I run the ng implementation and looking in my browser debugger I see the lack of **Authorization: Basic ...** in the request and the response I get from the server is 
**Full authentication is required to access this resource**

Relevant snippets of code below: -
```
app.config(['OAuthProvider', 'OAuthTokenProvider', function(OAuthProvider, OAuthTokenProvider) {
  OAuthProvider.configure({
      baseUrl: 'http://192.168.56.2:8080',
      clientId: 'clientId',
      clientSecret: 'clientSecret', // optional
      grantPath: '/oauth/token',
      revokePath: '/oauth/revoke'
  });

  OAuthTokenProvider.configure({
      name: 'token',
      options: {
          secure: false
      }
  });
}]);
```

```
var user = {username: 'username', password: 'password'}
OAuth.getAccessToken(user);
```

The data auth attributes end up being FORM data.

Is there something fundamental I am missing here.  Your help would be appreciated, I am new to oAuth.

Regards
Peter

**Comment by joaogranado** [comment]
Hey @PeterSawyer. You're problem relies on the fact you're expecting the pair `clientId:clientSecret` using the Basic authentication scheme, which is not supported for now. `clientId` and `clientSecret` are being sent on the request body. It is related with #43, since it's needed to add support for other authentication schemes. However you can fix this with a decorator and you're free to submit a PR for this!

**Comment by PeterSawyer** [comment]
Thanks mate.  I am now waiting on other dev dude to remove Basic Auth as the preferred solution.  Will give final comment and resolution hopefully in a week or 2.

**Comment by PeterSawyer** [comment]
Just a bit of closure here.

We **removed basic auth** from the Java server Spring-boot.  Then we ended up with some CORRS issues, specifically on **pre-flight OPTIONS**.  This stumped us for a while not knowing where to do what, but in the end another mod on the server (see below) solved this.

```
if (request.getMethod().equalsIgnoreCase("OPTIONS")) {
    log.info("GOT OPTIONS REQUEST");
    response.setStatus(HttpServletResponse.SC_OK);
} else {
    chain.doFilter(req, res);
}
```

Thanks for your assistance @joaogranado 

Peter
