### ISSUE TITLE
Revoking token should include token_type_hint in request body

### ISSUE THREAD

**Issue by jguittard** [seegno/angular-oauth2#64]
According to https://tools.ietf.org/html/rfc7009, paragraph 2.1, a *"token_type_hint may be included in the body to _help the authorization server to optimize the token lookup"*.
In OAuthProvider::revokeToken, if a refresh_token, it's passed as the token value. If not, the access_token value is set.
Could be helpful if the token_type_hint was added to the body and has, according to RFC, **refresh_token** or **access_token** value.

**Comment by ruipenso** [comment]
Duplicates #16.

Thanks anyway :)
