### ISSUE TITLE
Authorization header is always sent

### ISSUE THREAD

**Issue by SamiSammour** [seegno/angular-oauth2#69]
I have an issue concerning the interceptor, my problem is that it is adding the Authorization header to all requests including the getAccessToken & getRefreshToken, and this triggers a preflight request which is not supported from the server side.
I had to add the following code in the interceptor:
```
request: function(config) {
    // don't add the authorization header when the client is requesting a new token or refreshing one.
    if (angular.isDefined(config.data)) {
        var data = queryString.parse(config.data);
        if (angular.isDefined(data.grant_type) && (data.grant_type === 'password' || data.grant_type === 'refresh_token')) {
            return config;
        }
    }
    if (OAuthToken.getAuthorizationHeader()) {
        config.headers = config.headers || {};
        config.headers.Authorization = OAuthToken.getAuthorizationHeader();
    }
    return config;
}
```

**Comment by Anisotropic** [comment]
My problem is that it added the Authorization header to all request without exclusion!   In my case it adds this header to the request to Amazon AWS and those it failed.

**Comment by SamiSammour** [comment]
I solved my problem by creating my own interceptor 
```javascript
'use strict';

angular.module('app')
.factory('authorizationInterceptor', function() {
  return {
    request: function(config) {
      // don't add the authorization header when the client is requesting a new token or refreshing one.
      if (angular.isDefined(config.data)) {
        var data = queryString.parse(config.data);
        if (angular.isDefined(data.grant_type) && (data.grant_type === 'password' || data.grant_type === 'refresh_token')) {
          if (angular.isDefined(config.headers.Authorization)) {
            delete config.headers.Authorization;
          }
        }
      }
      return config;
    }
  };
});
```
and added it in my config
```javascript
$httpProvider.interceptors.push('authorizationInterceptor');
```

**Comment by Anisotropic** [comment]
Yes, i solved my problem in similar way - by creating the interceptor which removes authorization header if "config.url" contains "amazonaws.com". But it will be good, if there will be some flag that removes authorization headers from  the request. Like $http.get('/someUrl', { authorizationHeaders:"false" })...

**Comment by charleston10** [comment]
Close issue please
