### ISSUE TITLE
Basic Authentication doesn't work for refresh tokens

### ISSUE THREAD

**Issue by femiveys** [seegno/angular-oauth2#74]
There are 2 ways to identify a client: Basic Authentication or with client_id and client_secret. See https://tools.ietf.org/html/rfc6749#section-2.3.1 and especially:
>   Including the client credentials in the request-body using the two
>   parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
>   to directly utilize the HTTP Basic authentication scheme (or other
>   password-based HTTP authentication schemes).  The parameters can only
>   be transmitted in the request-body and MUST NOT be included in the
>   request URI.

For requesting a token, this module supports adding the Basic ```Authorization``` header. Good.

However, for refreshing the token, one cannot customize the headers and thus it is **impossible to use the recommended Basic ```Authorization``` header**. Not good.
Additionally, the interceptor will send the old (invalid) token in that header.
So even if we would be able to set the ```Authorization``` header to (for example) ```Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW```, the **interceptor will overwrite it with the old token** to (for example) ```Baerer tGzv3JOkF0XG5Qx2TlKWIA```

So to fix this bug, we need to:

1. Update the interceptor to not set the  ```Authorization``` header for refresh token requests.
2. Make sure the headers can be changed for refresh token

**Comment by girod** [comment]
I open an issue (#57) on the same problem.
I correct the issue using a buffer to resend all the requests with the new token.

**Comment by ruipenso** [comment]
@femiveys Can you check if #77 works for your scenario?

**Comment by ruipenso** [comment]
@femiveys The latest release 3.1.0 fixes this.

**Comment by femiveys** [comment]
Thanks, I confirm it is fixed.

**Comment by ruipenso** [comment]
@femiveys Cool :)

**Comment by ruipenso** [comment]
@femiveys We needed to revert and re-introduce the changes in a major version (4.0.0) due to BC. See this (comment)[https://github.com/seegno/angular-oauth2/pull/77#issuecomment-183305389].
